# Generated by Django 4.2.27 on 2026-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
